name: Pick Reviewer

on:
  pull_request:
    types:
      - opened

jobs:
  select-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Debug Repository Checkout
      run: |
        ls -al

    - name: Update GitHub CLI
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh --version
        gh extension install mislav/gh-pr --version 0.11.0

    - name: Read Config File
      id: read-config
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        config_file=.github/reviewers.json
        if [ -f "$config_file" ]; then
          echo "::set-output name=config_exists::true"
          cat "$config_file"
        else
          echo "::set-output name=config_exists::false"
        fi

    - name: Debug Config File
      if: steps.read-config.outputs.config_exists == 'true'
      run: |
        echo "Config Content: ${{ steps.read-config.outputs.stdout }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        python -m pip install --upgrade pip
        pip install jq
        pip install gh

    - name: Determine Reviewer
      env:
        GH_TOKEN: ${{ github.token }}
      id: determine-reviewer
      if: steps.read-config.outputs.config_exists == 'true'
      run: |
        config=$(echo "${{ steps.read-config.outputs.stdout }}" | jq -r '.reviewers')
        pr_author=$(gh pr view ${{ github.event.number }} --json user.login --json-format=json | jq -r '.user.login')

        current_reviewers=$(gh pr review-list -R $GITHUB_REPOSITORY --json state,author.login --json-format=json | jq -r '.[] | select(.state == "APPROVED").author.login' | sort | uniq -c | sort -n | awk '{print $2}')

        selected_reviewer=$(python -c "
        import json

        config = json.loads('''$config''')
        current_reviewers = '''$current_reviewers'''.split()
        pr_author = '''$pr_author'''

        # Filter out the PR author
        current_reviewers = [reviewer for reviewer in current_reviewers if reviewer != pr_author]

        reviewer_counts = {reviewer: 0 for reviewer in config}

        for reviewer in current_reviewers:
            if reviewer in reviewer_counts:
                reviewer_counts[reviewer] += 1

        selected_reviewer = min(reviewer_counts, key=reviewer_counts.get)
        print(selected_reviewer)
        ")

        echo "::set-output name=selected_reviewer::$selected_reviewer"

    - name: Debug Determine Reviewer
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Config: $config"
        echo "PR Author: $pr_author"
        echo "Current Reviewers: $current_reviewers"
        echo "Selected Reviewer: $selected_reviewer"

    - name: Add Reviewer to Pull Request
      if: steps.determine-reviewer.outputs.selected_reviewer != ''
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr request-review -R $GITHUB_REPOSITORY -B $GITHUB_HEAD_REF -r "${{ steps.determine-reviewer.outputs.selected_reviewer }}"
