name: "Docs Search Scraper"

on:
  push:
    branches: "main"
  schedule:
    - cron: '00 04 * * *'

jobs:
  scrape:
    name: "Scrape"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3   # You MUST checkout your repository first!

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          # The secret containing your Typesense API key. Required.
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
      
          # The hostname or IP address of your Typesense server. Required.
          host: panel.nodes.arion2000.xyz
      
          # The port on which your Typesense server is listening. Optional. Default: 8108.
          port: 8108
      
          # The protocol to use when connecting to your Typesense server. Optional. Default: http.
          protocol: http
      
          # The path to your DocSearch config file. Optional. Default: docsearch.config.json.
          config: docsearch.config.json
